
services:
  pfsense-fw:
    image: ubuntu
    container_name: pfsense-fw
    privileged: true # Necesario para manipular reglas de iptables/enrutamiento
    networks:
      vpn_net:
        ipv4_address: 172.10.0.2
      services_net:
        ipv4_address: 172.20.0.2
      production_net:
        ipv4_address: 172.30.0.2
      development_net:
        ipv4_address: 172.40.0.2
    command: |
      bash -c "
      apt-get update && apt-get install -y iproute2 &&
      sysctl -w net.ipv4.ip_forward=1 &&
      tail -f /dev/null
      "
  dns_server:
    image: ubuntu/bind9:latest
    container_name: dns_server
    environment:
    - BIND9_USER=root
    networks:
      services_net:
        ipv4_address: 172.20.0.10
    volumes:
      - ./named.conf.local:/etc/bind/named.conf.local
      - ./db.produccion:/etc/bind/db.produccion
      - ./db.desarrollo:/etc/bind/db.desarrollo
    restart: always

networks:
  vpn_net:
    external: true
  services_net:
    external: true
  production_net:
    external: true
  development_net:
    external: true